channels:
  - conda-forge
dependencies:
  - python>=3.6
  - sphinx>=1.6
  - pandoc
  - nbconvert
  - ipykernel
  - xarray
  - pip:
    - guzzle_sphinx_theme
    - nbsphinx
    - git+https://github.com/gwin-zegal/lerp.git
