channels:
  - conda-forge
dependencies:
  - python>=3.6
  - sphinx==1.6.2
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - guzzle_sphinx_theme
    - nbsphinx
    - git+https://github.com/gwin-zegal/lerp.git
